language: ruby
rvm:
  - 1.9.3
before_install:
  - gem install bundler
bundler_args: --without production
before_script:
  - cp config/database.example.yml config/database.yml
  - rake db:create:all db:schema:load
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
services:
  - mongodb
