STRIPE_SECRET_KEY: 565HDBL67LviJs1aYEiDeihF3sOTmPr8
STRIPE_PUBLISHABLE_KEY: pk_nW2unZUBc2NZ52dWHf1RU8TAmI0dP
DEVELOPMENT_EMAIL_ADDRESS: <your email address>
SECRET_TOKEN: some-long-secret-token-at-least-30-characters
S3_ACCESS_ID: fake
S3_ACCESS_KEY: fake
S3_BUCKET_NAME: fake
